### ISSUE TITLE
Update Filebeat module download URL

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-ansible#1130]
It is necessary to update the URL from which the Filebeat module is downloaded to allow deployments in demo environments, currently only the module is downloaded from production, and when we have a Filebeat module in pre-release and we are deploying demo environment from pre-release.

https://github.com/wazuh/wazuh-ansible/blob/4b385eeb7e3a29ccdc3fadf577355f884fc81b1d/roles/wazuh/ansible-filebeat-oss/defaults/main.yml#L11

**Comment by davidcr01** [comment]
The Filebeat module URL has been updated:

```
filebeat_module_package_url: https://packages-dev.wazuh.com/pre-release/filebeat
```

**Comment by davidcr01** [comment]
# Update Report

## Workaround

To adapt the Filebeat module URL to the repository, the `filebeat_module_package_url` variable has been moved to the `repo.yml` and `repo_pre-release.yml` from the `roles/wazuh/ansible-filebeat-oss/defaults/main.yml` file. 

In the `repo.yml`:
```yml
filebeat_module_package_url: https://packages.wazuh.com/4.x/filebeat
```

In the `repo_pre-release.yml`:
```yml
filebeat_module_package_url: https://packages-dev.wazuh.com/pre-release/filebeat
```

This variable will be chosen thanks to the `check_packages` task. But, to include these variables, it is necessary to modify the `roles/wazuh/ansible-filebeat-oss/tasks/main.yml`:

```yml
---
- include_vars: ../../vars/repo_vars.yml

- include_vars: ../../vars/repo.yml
  when: packages_repository == 'production'

- include_vars: ../../vars/repo_pre-release.yml
  when: packages_repository == 'pre-release'
```
