### ISSUE TITLE
Bug registering the Windows agent in demo environment

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-ansible#1155]
## Description

In https://github.com/wazuh/wazuh-automation/issues/1449, we have found a issue when registering the Windows agent in the demo environment. The generated error is the following:

```console
TASK [Add Windows Agent to Windows group] **************************************
fatal: [13.52.9.110]: FAILED! => {
    "changed": true,
    "cmd": "/var/ossec/bin/agent_groups -a -g windows -i  -q",
    "delta": "0:00:00.969206",
    "end": "2023-12-07 16:06:25.637602",
    "rc": 2,
    "start": "2023-12-07 16:06:24.668396"
}

STDERR:

usage: agent_groups.py [-h] [-l] [-c] [-a] [-f] [-s] [-S] [-r] [-i AGENT_ID]
                       [-g GROUP_ID] [-q] [-d] [-u]
agent_groups.py: error: argument -i/--agent-id: expected one argument


MSG:

non-zero return code
```

The related code is the following:

```yml
- name: Add Windows Agent to Windows group
  shell: /var/ossec/bin/agent_groups -a -g windows -i {{ windows_id.stdout }} -q
  when:
    - inventory_hostname in groups['master1']
 ```

It seems that the Windows agent ID is not being fetched, although it is deployed in the pipeline.

## Tasks

- [x] Investigate the problem
- [x] Apply the fix
- [ ] Validate the fix
