### ISSUE TITLE
Incorrect permissions for local rules directory

### ISSUE THREAD

**Issue by juresaht2** [wazuh/wazuh-ansible#1201]
There is a bug here:
https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L115

```yaml
- name: Adding local rules files
  copy: src="{{ wazuh_manager_config.ruleset.rules_path }}"
        dest="{{ wazuh_dir }}/etc/rules/"
        owner=wazuh
        group=wazuh
        mode=0640
  notify: restart wazuh-manager
  tags:
    - init
    - config
    - rules
 ```

This task is copying a directory, so the permissions must include the executable permission to allow Wazuh to access the files inside the directory.

Of course you probably don't want to put executable permissions on the files inside. I went with:
```yaml
    mode: "u=rwX,g+rX,g-w,o-rwX"
```
