### ISSUE TITLE
Multi-node deployment failed : cluster status is 'yellow'

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-ansible#1367]
## Description

During the E2E tests for 4.9.0
- https://github.com/wazuh/wazuh/issues/24838

It happened that the execution of the `wazuh-production-ready.yml ` playbook failed in the task `Wait for Wazuh indexer API (Private IP)` after the 24 attempts 

<details><summary>Log</summary>
<p>

```
fatal: [wi1]: FAILED! => {
    "attempts": 24,
    "changed": false,
    "content": "1721917656 14:27:36 wazuh yellow 2 2 true 4 4 0 0 4 0 - 50.0%\n",
    "content_length": "62",
    "content_type": "text/plain; charset=UTF-8",
    "cookies": {},
    "cookies_string": "",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "body": null,
            "body_format": "raw",
            "ca_path": null,
            "ciphers": null,
            "client_cert": null,
            "client_key": null,
            "creates": null,
            "decompress": true,
            "dest": null,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "remote_src": false,
            "removes": null,
            "return_content": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                200,
                401
            ],
            "timeout": 4,
            "unix_socket": null,
            "unredirected_headers": [],
            "unsafe_writes": false,
            "url": "https://10.88.0.46:9200/_cat/health/",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "admin",
            "use_gssapi": false,
            "use_netrc": true,
            "use_proxy": true,
            "user": "admin",
            "validate_certs": false
        }
    },
    "msg": "OK (62 bytes)",
    "redirected": false,
    "status": 200,
    "url": "https://10.88.0.46:9200/_cat/health/"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
wi1                        : ok=32   changed=13   unreachable=0    failed=1    skipped=51   rescued=0    ignored=0   
wi2                        : ok=23   changed=8    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0   
```

</p>
</details> 

The environment consisted of two Debian 12 nodes where the Wazuh Indexer nodes will be installed.
These are the modified files: the `hosts` file was updated with new names, and the playbook reference to a third indexer node was removed

<details><summary>Details</summary>
<p>

```
root@cdca68079576:/etc/ansible/roles/wazuh-ansible# cat /etc/ansible/hosts 
wi1 ansible_host=10.88.0.46 private_ip=10.88.0.46 indexer_node_name=node-1
wi2 ansible_host=10.88.0.47 private_ip=10.88.0.47 indexer_node_name=node-2
dashboard  ansible_host=10.88.0.48 private_ip=10.88.0.48
manager ansible_host=10.88.0.44 private_ip=10.88.0.44
worker  ansible_host=10.88.0.45 private_ip=10.88.0.45

[wi_cluster]
wi1
wi2

[all:vars]
ansible_ssh_user=root
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
```

```
root@cdca68079576:/etc/ansible/roles/wazuh-ansible# cat /etc/ansible/roles/wazuh-ansible/playbooks/wazuh-production-ready.yml 
---
# Certificates generation
    - hosts: wi1
      roles:
        - role: ../roles/wazuh/wazuh-indexer
          indexer_network_host: "{{ private_ip }}"
          indexer_cluster_nodes:
            - "{{ hostvars.wi1.private_ip }}"
            - "{{ hostvars.wi2.private_ip }}"
          indexer_discovery_nodes:
            - "{{ hostvars.wi1.private_ip }}"
            - "{{ hostvars.wi2.private_ip }}"
          perform_installation: false
      become: no
      vars:
        indexer_node_master: true
        instances:
          node1:
            name: node-1       # Important: must be equal to indexer_node_name.
            ip: "{{ hostvars.wi1.private_ip }}"   # When unzipping, the node will search for its node name folder to get the cert.
            role: indexer
          node2:
            name: node-2
            ip: "{{ hostvars.wi2.private_ip }}"
            role: indexer
          node4:
            name: node-4
            ip: "{{ hostvars.manager.private_ip }}"
            role: wazuh
            node_type: master
          node5:
            name: node-5
            ip: "{{ hostvars.worker.private_ip }}"
            role: wazuh
            node_type: worker
          node6:
            name: node-6
            ip: "{{ hostvars.dashboard.private_ip }}"
            role: dashboard
      tags:
        - generate-certs

# Wazuh indexer cluster
    - hosts: wi_cluster
      strategy: free
      roles:
        - role: ../roles/wazuh/wazuh-indexer
          indexer_network_host: "{{ private_ip }}"
      become: yes
      become_user: root
      vars:
        indexer_cluster_nodes:
          - "{{ hostvars.wi1.private_ip }}"
          - "{{ hostvars.wi2.private_ip }}"
        indexer_discovery_nodes:
          - "{{ hostvars.wi1.private_ip }}"
          - "{{ hostvars.wi2.private_ip }}"
        indexer_node_master: true
        instances:
          node1:
            name: node-1       # Important: must be equal to indexer_node_name.
            ip: "{{ hostvars.wi1.private_ip }}"   # When unzipping, the node will search for its node name folder to get the cert.
            role: indexer
          node2:
            name: node-2
            ip: "{{ hostvars.wi2.private_ip }}"
            role: indexer
          node4:
            name: node-4
            ip: "{{ hostvars.manager.private_ip }}"
            role: wazuh
            node_type: master
          node5:
            name: node-5
            ip: "{{ hostvars.worker.private_ip }}"
            role: wazuh
            node_type: worker
          node6:
            name: node-6
            ip: "{{ hostvars.dashboard.private_ip }}"
            role: dashboard

# Wazuh cluster
    - hosts: manager
      roles:
        - role: "../roles/wazuh/ansible-wazuh-manager"
        - role: "../roles/wazuh/ansible-filebeat-oss"
          filebeat_node_name: node-4
      become: yes
      become_user: root
      vars:
        wazuh_manager_config:
          connection:
              - type: 'secure'
                port: '1514'
                protocol: 'tcp'
                queue_size: 131072
          api:
              https: 'yes'
          cluster:
              disable: 'no'
              node_name: 'master'
              node_type: 'master'
              key: 'c98b62a9b6169ac5f67dae55ae4a9088'
              nodes:
                  - "{{ hostvars.manager.private_ip }}"
              hidden: 'no'
        wazuh_api_users:
          - username: custom-user
            password: SecretPassword1!
        filebeat_output_indexer_hosts:
                - "{{ hostvars.wi1.private_ip }}"
                - "{{ hostvars.wi2.private_ip }}"

    - hosts: worker
      roles:
        - role: "../roles/wazuh/ansible-wazuh-manager"
        - role: "../roles/wazuh/ansible-filebeat-oss"
          filebeat_node_name: node-5
      become: yes
      become_user: root
      vars:
        wazuh_manager_config:
          connection:
              - type: 'secure'
                port: '1514'
                protocol: 'tcp'
                queue_size: 131072
          api:
              https: 'yes'
          cluster:
              disable: 'no'
              node_name: 'worker_01'
              node_type: 'worker'
              key: 'c98b62a9b6169ac5f67dae55ae4a9088'
              nodes:
                  - "{{ hostvars.manager.private_ip }}"
              hidden: 'no'
        filebeat_output_indexer_hosts:
                - "{{ hostvars.wi1.private_ip }}"
                - "{{ hostvars.wi2.private_ip }}"

# Wazuh dashboard node
    - hosts: dashboard
      roles:
        - role: "../roles/wazuh/wazuh-dashboard"
      become: yes
      become_user: root
      vars:
        indexer_network_host: "{{ hostvars.wi1.private_ip }}"
        indexer_cluster_nodes:
          - "{{ hostvars.wi1.private_ip }}"
          - "{{ hostvars.wi2.private_ip }}"
        dashboard_node_name: node-6
        wazuh_api_credentials:
          - id: default
            url: https://{{ hostvars.manager.private_ip }}
            port: 55000
            username: custom-user
            password: SecretPassword1!
        ansible_shell_allow_world_readable_temp: true

```

</p>
</details> 

## DoD

- [ ] Reproduce the issue
- [ ] Find the root cause
- [ ] Propose a fix and/or justify the failure with the environment of test
