### ISSUE TITLE
404 error when downloading the Java JDK rpm

### ISSUE THREAD

**Issue by LuisGi93** [wazuh/wazuh-ansible#172]
Hi team,
Right now when we deploy using our playbooks Elasticsearch or Kibana in CentOS the following error will happen:
![image](https://user-images.githubusercontent.com/17405573/56606199-ff8fe200-6605-11e9-98fa-062acf43314f.png)
The error happens when we download the Java JDK installer:
```
- when: elasticsearch_install_java
  block:
    - name: RedHat/CentOS/Fedora | download Oracle Java RPM
      get_url:
        url: https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.rpm
        dest: /tmp/jre-8-linux-x64.rpm
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
      register: oracle_java_task_rpm_download
```
