### ISSUE TITLE
"Make sure Elasticsearch is running before proceeding" test is broken

### ISSUE THREAD

**Issue by kravietz** [wazuh/wazuh-ansible#184]
The test in `roles/wazuh-ansible/roles/elastic-stack/ansible-elasticsearch/tasks/main.yml` line 87 only works if the `elasticsearch_network_host` is set to `localhost` but ElasticSearch uses this parameter to configure its bind address, so in many real-world instances it will be set to `0.0.0.0` or `::`, in which case the test fails.

```
- name: Make sure Elasticsearch is running before proceeding
  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300
  tags:
    - configure
    - init           
```
