### ISSUE TITLE
failed to install wazuh manager with ansible 

### ISSUE THREAD

**Issue by chengjz** [wazuh/wazuh-ansible#187]
Hi,

Followed this https://documentation.wazuh.com/3.x/deploying-with-ansible/guide/install-wazuh-server.html. 
I got some problem to run install wazuh-manager command in the ansible galaxy provided by wazuh.  

### failed task:
```yml

- name: Install wazuh-manager, wazuh-api and expect
  package: pkg={{ item }} state={{ wazuh_manager_package_state }}
  with_items:
    - wazuh-manager
    - wazuh-api
    - expect
  register: wazuh_manager_main_packages_installed
  until: wazuh_manager_main_packages_installed is succeeded
  when:
    - not (ansible_distribution in ['CentOS','RedHat'] and ansible_distribution_major_version|int < 6)
  tags:
    - init
```
### error msg: 
``` jason
failed: [10.196.17.166] (item=wazuh-manager) => {
    "ansible_loop_var": "item", 
    "attempts": 3, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_downgrade": false, 
            "autoremove": false, 
            "bugfix": false, 
            "conf_file": null, 
            "disable_excludes": null, 
            "disable_gpg_check": false, 
            "disable_plugin": [], 
            "disablerepo": [], 
            "download_dir": null, 
            "download_only": false, 
            "enable_plugin": [], 
            "enablerepo": [], 
            "exclude": [], 
            "install_repoquery": true, 
            "install_weak_deps": true, 
            "installroot": "/", 
            "list": null, 
            "lock_timeout": 0, 
            "name": [
                "wazuh-manager"
            ], 
            "pkg": "wazuh-manager", 
            "releasever": null, 
            "security": false, 
            "skip_broken": false, 
            "state": "latest", 
            "update_cache": false, 
            "update_only": false, 
            "use_backend": "auto", 
            "validate_certs": true
        }
    }, 
    "item": "wazuh-manager", 
    "msg": "No package matching 'wazuh-manager' found available, installed or updated", 
    "rc": 126, 
    "results": [
        "No package matching 'wazuh-manager' found available, installed or updated"
    ]
}
```
