### ISSUE TITLE
Implement playbooks to deploy an Elasticsearch 7 cluster with xpack security options

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#189]
Hi team,

It'd be necessary to implement the required tasks and roles for deploying an Elasticsearch cluster with `xpack security` and SSL enabled.

- [x] Add the ability to set up `xpack` security options for Elastic 7.
- [x] Add the ability to generate certificated and distribute the `CA` between the nodes.
- [x] Secure Filebeat with certificates signed by the same CA.
- [x] Secure Kibana using users.

This issue will be edited in order to add more details.

Cheers

**Comment by manuasir** [comment]
Hi team,

This task has been started approaching these main points:

- Modify the Elasticsearch role and add variables for being able to enable XPACK security and SSL protocol.
- Modify the Kibana role for being able to enable SSL and security.
- Set the necessary variables for being able to generate certificates and a CA (only **one** node of the cluster should do this).
- Modify the `elasticsearch.yml` template so the options can be added.

The template should include the logic for the previous work. The tricky part is that a `instances.yml` file is required for generating the certificates, and both IP and hostnames should of each cluster master node have to be known previously. Probably Ansible `Facts` will be used so we can get the hostname.

The next steps will be the implementation of the distribution of the certificates and CA from one node to the others. Probably the Ansible [synchronization](https://docs.ansible.com/ansible/latest/modules/synchronize_module.html) method will be used for approaching this.

Cheers

**Comment by manuasir** [comment]
#### Updated 06/29/2019 CEST

The development of this task is being done in [this branch](https://github.com/wazuh/wazuh-ansible/tree/elk-security).

- New tasks were added to implement the logic of the certificates generation:

```
- name: Write the instances.yml file in the selected node
  instances_file:
    src: instances.yml.j2
    dest: "/usr/share/elasticsearch/instances.yml"
  tags:
    - config
  when: 
    - node_generate_certs
    - elasticsearch_xpack_security
```

This is the first approach of the template:

```

# {{ ansible_managed }}

{% if node_generate_certs %}
instances:
{% for item in elasticsearch_cluster_nodes %}
    ip: {{ item.ip }}
    - "{{ item.name }}"
{% endfor %}
{% endif %}
```

Also, it's necessary to implement a way to detect that the file _already_ exists or not:
```
- name: Write the instances.yml file in the selected node
  instances_file:
    src: instances.yml.j2
    dest: "/usr/share/elasticsearch/instances.yml"
  tags:
    - config
  when: 
    - node_generate_certs
    - elasticsearch_xpack_security
```

I'm implementing this focusing on *variables*. This is the example of playbook I'm using for testing:

```
- hosts: 172.16.0.161
  roles:
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '172.16.0.161', node_generate_certs: true, elasticsearch_bootstrap_node: true, elasticsearch_cluster_nodes: ['172.16.0.162','172.16.0.163','172.16.0.161']}

- hosts: 172.16.0.162
  roles:
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '172.16.0.162', elasticsearch_master_candidate: true, elasticsearch_cluster_nodes: ['172.16.0.162','172.16.0.163','172.16.0.161']}

- hosts: 172.16.0.163
  roles:
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '172.16.0.163', elasticsearch_master_candidate: true, elasticsearch_cluster_nodes: ['172.16.0.162','172.16.0.163','172.16.0.161']}
```

Notice the `node_generate_certs` in the bootstrap node. The certificates and the `instances.yml` should only be generated in there.

The next steps would be the propagation of the certificates over the rest of the instances, probably not a hard part. The most tricky tasks will be the catch of the hostnames and IPs of each instance, both required for the `instances.yml` file. I'll keep this issue updated and will tell more details about the progression of the task. Also, don't hesitate to suggest any new idea.

Cheers
