### ISSUE TITLE
Unsupported proxy scheme

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-ansible#214]
I'm receiving the following error when running the wazuh-agent playbook.  How do I resolve?

TASK [/etc/ansible/roles/roles/wazuh/ansible-wazuh-agent : Debian/Ubuntu | Installing Wazuh repository key] **********************************************************************************
task path: /etc/ansible/roles/roles/wazuh/ansible-wazuh-agent/tasks/Debian.yml:24
fatal: [192.168.x.x]: FAILED! => {"changed": false, "msg": "Unsupported proxy scheme: https. Currently ansible only supports HTTP proxies.", "status": -1, "url": "https://packages.wazuh.com/key/GPG-KEY-WAZUH"}

**Comment by jm404** [comment]
Hi @alphaDev23,

In order to replicate your case, I tested the installation on Debian 8 and Debian 9. In both cases my setup run shows no error in the step you mention.

According to Ansible documentation (https://docs.ansible.com/ansible/2.6/modules/apt_key_module.html), there is no restriction in the  `apt_key` module about using https in the URL.

That makes me suspect about your proxy configuration and the possibility of having an outdated GPG Key of Wazuh (we recently renewed it).

#### Checking GPG Key

First, check if you have an outdated GPG key of Wazuh by running

``` 
apt-key list | grep -i wazuh -B 3 -A 3
```
Which will output the Wazuh GPG key in case you have it installed, mine shows the newer version that expires in 2027:

![image](https://user-images.githubusercontent.com/46649922/62446549-42b03400-b763-11e9-9ee7-dd5a7006976b.png)

If yours is expired, you can delete it by running:

```
apt-key del 2911 1145
```

*Note:* Those numbers correspond to the last 8 digits of the GPG key showed before:

![image](https://user-images.githubusercontent.com/46649922/62446719-c702b700-b763-11e9-8df5-f3a9651d5dea.png)

Then, run again your playbook and it should work fine.

#### Checking Proxy Configuration

If you are running behind a proxy, you can modify the *Debian/Ubuntu | Installing Wazuh repository key* task to add the environment variables and the validate_certs like this:

```
- name: Debian/Ubuntu | Installing Wazuh repository key
  apt_key: 
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    validate_certs: false
  environment:
    http_proxy: http://IP:PORT
    https_proxy: https://IP:PORT
  when:
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 14)
``` 

**Security note:** When using `validate_certs: false` and according to Ansible documentation:
 > SSL certificates for the target URL will not be validated. This should only be used on personally controlled sites using self-signed certificates.

Where `IP` and `PORT` are the ones of your proxy

I hope one of these options fixes your problem, please let me know if you have any doubts or errors.

Best regards,

Jose
