### ISSUE TITLE
Add a way to setup API auth on every node

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#268]
Hi team,

Recently we added a new elasticsearch+xpack scenario to the molecule tests. In order to be able to reach the API from all the nodes in the cluster it is required a way to setup the API auth on every node.

Currently it is only enabled on the node with the tag `node_certs_generator`.

```
- name: Set elasticsearch bootstrap password
  shell: |
    set -o pipefail
    echo {{ elasticsearch_xpack_security_password }} | {{ node_certs_source }}/bin/elasticsearch-keystore add -xf bootstrap.password
  args:
    executable: /bin/bash
  when:
    - node_certs_generator
  tags: molecule-idempotence-notest
```

### Tasks

- [x] Create a task to setup API auth on any node

Regards.

**Comment by xr09** [comment]
After some brainstorming with the team members we're thinking of going all the way and allow the setup of new elasticsearch users from the playbook.

This is a rough preview of the definition:

```
users:
  anne:
    name: "anne"
    password: "secret"
    roles: [ "admin", "other_role1" ]
```
