### ISSUE TITLE
Elasticsearch API user creation is not working

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#272]
Hi team,

Recently with #270 we added support for creating new ES API users right from the playbook, but this is not working as expected.

It worked in a controlled environment because the test containers were already running a cluster in sync, but in a real deploy from scratch it does not work due to the cluster not being ready yet.

You'll get an error like this one:

```
"error" : {
    "root_cause" : [
      {
        "type" : "master_not_discovered_exception",
        "reason" : null
      }
    ],
```

So in order to fix this we'll need to tune this task to run only after the cluster is ready.

### Tasks
- [x] Delay task until cluster is ready
- [x] Test execution from scratch

Regards.

**Comment by xr09** [comment]
After a chat with @manuasir we're choosing to setup a task to wait until the cluster is ready and create the molecule user for the test environment within the custom tests.

**Comment by xr09** [comment]
In order to allow the user creation from both a real deploy and our molecule scenario we're opting to create two new variables for the molecule env. `molecule_api_host` and `molecule_api_runner`.

These will be used on the molecule playbook, `molecule_api_host` will point to the bootstrap node and `molecule_api_runner` will be set to `true` on the last node (Molecule has sequential execution)

```
---
- name: Converge
  hosts: node-1
  roles:
    - role: ../roles/elastic-stack/ansible-elasticsearch
      ...

- hosts: node-2
  roles:
    - role: ../roles/elastic-stack/ansible-elasticsearch
      ...
      molecule_api_runner: true

  vars:
    molecule_api_host: node-1
    ...
```

The task to create these users will check if these variables are defined and run only on the last host (i.e. `molecule_api_runner`).

In order to support a real deploy (with a parallel execution), we'll check for the non existence of these variables and execute the task on the bootstrap node, just adding a waiting task to query the cluster and only proceed when it is ready to accept API requests.

The wait task will be something like this: 

```
- name: "Wait for elastic cluster to be ready"
  uri:
    url: "http://127.0.0.1:9200/"
    user: somebody
    password: somepass
    validate_certs: no
    status_code: 200
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
```
