### ISSUE TITLE
Wazuh Agent installation forces the "-1" sufix on installation

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#309]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**
Any

**Is this a bug report or a feature requests?:**
Feature request

**What is the current behavior?**
Our installation task for wazuh-agent is 

```
- name: Linux CentOS/RedHat | Install wazuh-agent
  package: name=wazuh-agent-{{ wazuh_agent_version }}-1 state=present
  async: 90
  poll: 30
  when:
    - ansible_os_family|lower == "redhat"
  tags:
    - init
```

Note it forces the -1, causing it to fail with packages like `wazuh-agent-3.10.2-0`. This can be solved removing the `-1` in the task.

**What is the motivation/use case for changing the behavior?**

Avoid forcing the "-1" sufix to flex installations. Also, there are duplicated tasks for Wazuh Agent installation. It's required to fix them and update the conditionals.

**Description**: 

### Tasks

- [x] Remove the "-1" sufix

- [x] Verify conditionals

- [x] Update documentation if required

Best regards

Jose
