### ISSUE TITLE
Support multiple Elasticsearch output in ansible-logstash-role

### ISSUE THREAD

**Issue by MaxVerro** [wazuh/wazuh-ansible#31]
The parameters "elasticsearch_network_host" does not support multiple hosts. It would be nice to support this to benefit from the "LoadBalance" feature of elasticsearch outputs. 

> The loadbalance option is available for Redis, Logstash, and Elasticsearch outputs. The Kafka output handles load balancing internally.

Please see Logstash documentation:
https://www.elastic.co/guide/en/beats/packetbeat/current/logstash-output.html#loadbalance

**Comment by mjflve** [comment]
Hi @MaxVerro,

You're right this would be a good enhancement, we're adding this to our roadmap for the next release. Thanks!

Best Regards,

**Comment by madonius** [comment]
I would give it a try. Unfortunately I don't see a way of solving it, properly, without either some glue code or risking backwards compatibility.
i.e. I would propose introducing a variable `elasticsearch_network_hosts` which would contain a list of dictionaries containing a host and a port each.
```yaml
elasticsearch_network_hosts:
  - host: 'es1.example.com'
    http_port: 8080
  - host: 'es2.example.com'
    http_port: 8080
```
@rtnoyld do you see a better way of tackling that issue?

Cheers,
  /m
