### ISSUE TITLE
Default installation for Wazuh with no custom configuration 

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-ansible#332]
Hi all!

The current installation of Wazuh made using `wazuh-ansible` is not a clean-default one. In other words, it does not install a default `ossec.conf` but a customized one.

For example, when installing `wazuh-agent` we use a parameterized template 

The same case for _wazuh-manager_.

As it's parameterized, we set the values for the corresponding variables but we do not take into account the changes made in the default installed `ossec.conf` as it will always be overwritten.

**To Do**
- [x]  Bump version to Wazuh 3.11.
- [x] Adapt to the latest installation, the `ossec.conf` template  of:
- - [x] _wazuh-manager_ 
- - - [x] RHEL
- - - - [x] Centos7
- - - [x] Debian
----
- - [x] _wazuh-agent_ 
- - - [x] RHEL
- - - - [x] Centos7
- - - [x] Debian
- - - [x] Windows
----
- [x] Verify changes.

-----

- **`Note:`** This description may be modified in the future.

Kr,

Rshad

**Comment by rshad** [comment]
Working branch: [feature-332-default-installation](https://github.com/wazuh/wazuh-ansible/tree/feature-332-default-installation)

**Comment by rshad** [comment]
Hi all!

We applied the necessary changes to get the most approximated `ossec.conf` to the one we get by a default installation with Wazuh 3.11 for both  
- `wazuh-manager` 
- `wazuh-agent`.

The most notable configuration change is related to  `wazuh-manager` and that `vulnerability-detector` is not a `wodle` anymore, but it has its own section in `ossec.conf`.

-  _"vulnerability-detector"_ Template part.
 ```ruby
  <vulnerability-detector>
  {% if wazuh_manager_config.vulnerability_detector.enabled is defined %}
    <enabled>{{ wazuh_manager_config.vulnerability_detector.enabled }}</enabled>
  {% endif %}
  {% if wazuh_manager_config.vulnerability_detector.interval is defined %}
    <interval>{{ wazuh_manager_config.vulnerability_detector.interval }}</interval>
  {% endif %}
  {% if wazuh_manager_config.vulnerability_detector.ignore_time is defined %}
    <ignore_time>{{ wazuh_manager_config.vulnerability_detector.ignore_time }}</ignore_time>
  {% endif %}
  {% if wazuh_manager_config.vulnerability_detector.run_on_start is defined %}
    <run_on_start>{{ wazuh_manager_config.vulnerability_detector.run_on_start }}</run_on_start>
  {% endif %}
  {% if wazuh_manager_config.vulnerability_detector.providers is defined %}
  {% for provider_ in wazuh_manager_config.vulnerability_detector.providers %}
    <provider name={{ provider_.name }}>
      {% if provider_.enabled is defined %}
      <enabled>{{ provider_.enabled }}</enabled>
      {% endif %}


      {% if provider_.os is defined %}
      {% for os_ in provider_.os %}
      <os>{{ os_ }}</os>
      {% endfor %}
      {% endif %}


      {% if provider_.update_from_year is defined %}
      <update_from_year>{{ provider_.update_from_year }}</update_from_year>
      {% endif %}


      {% if provider_.update_interval is defined %}
      <update_interval>{{ provider_.update_interval }}</update_interval>
      {% endif %}
    </provider>
  {% endfor %}
  {% endif %}
  </vulnerability-detector>
```

- _vulnerability-detector_ Template's variables
```yaml
  vulnerability_detector:
    enabled: 'no'
    interval: '5m'
    ignore_time: '6h'
    run_on_start: 'yes'
    providers:
      - enabled: 'no'
        os:
          - 'precise'
          - 'trusty'
          - 'xenial'
          - 'bionic'
        update_interval: '1h'
        name: '"canonical"'
      - enabled: 'no'
        os:
          - 'wheezy'
          - 'stretch'
          - 'jessie'
          - 'buster'
        update_interval: '1h'
        name: '"debian"'
      - enabled: 'no'
        update_from_year: '2010'
        update_interval: '1h'
        name: '"redhat"'
      - enabled: 'no'
        update_from_year: '2010'
        update_interval: '1h'
        name: '"nvd"'
```

Kr,

Rshad
