### ISSUE TITLE
Oracle Java < Java OpenJDK 8

### ISSUE THREAD

**Issue by JohnSeabourn** [wazuh/wazuh-ansible#345]
The script tries to use a dead PPA from Oracle.  Need to update the roles for Elastic and Logstash to use OpenJDK instead for all deployment types.

**Comment by xr09** [comment]
You're right John, that link from Oracle no longer seems to be active. We'll look into this. Thanks for reporting!

**Comment by xr09** [comment]
### Description

The Wazuh Agent role is using a dead link for Oracle Java

```

- name: RedHat/CentOS/Fedora | download Oracle Java RPM
  get_url:
    url: https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.rpm
    dest: /tmp/jre-8-linux-x64.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
  register: oracle_java_task_rpm_download
  until: oracle_java_task_rpm_download is succeeded
  when:
    - wazuh_agent_config.cis_cat.disable == 'no'
    - wazuh_agent_config.cis_cat.install_java == 'yes'
  tags:
    - init
```


### Tasks

- [ ] Switch role to use OpenJDK
- [ ] Test role execution
