### ISSUE TITLE
[Wazuh-agent] Authd role cannot be used with Wazuh-on-kubernetes

### ISSUE THREAD

**Issue by Born2Bake** [wazuh/wazuh-ansible#384]
Hi,

If you instal Wazuh on kubernetes, manager is divided into masters(1515, 55000) and workers (1514) therefore, wazuh_manager address shall be worker-ip address and wazuh-agent-authd ip address should be master-ip address. Can I add my own var to overcome this issue? Thank you

```
vars:
    wazuh_managers:
      - address: worker-ip
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: foo
    wazuh_agent_authd:
      enable: true
      **_address: master-ip-variable is needed_**
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
```

**Comment by Zenidd** [comment]
Hello @Born2Bake,

> If you instal Wazuh on kubernetes, manager is divided into masters(1515, 55000) and workers (1514) therefore, wazuh_manager address shall be worker-ip address and wazuh-agent-authd ip address should be master-ip address. Can I add my own var to overcome this issue? Thank you

Currently, the `wazuh-agent` ansible role is useful both in Kubernetes with or without loadbalancer environments and also in contexts different from kubernetes:

### Wazuh on kubernetes with loadbalancer

- In case your Wazuh on kubernetes environment uses a loadbalancer whereby the agents have to interact with the (`master|workers`) managers, you should use this loadbalancer IP as the `address:` value:
```YAML
vars:
    wazuh_managers:
      - address: loadbalancer-ip
        port: 1514
        protocol: tcp
```

- Windows and linux agents registrastion tasks point to the first declared wazuh_manager address:
https://github.com/wazuh/wazuh-ansible/blob/52a81af988a00abd60483f1ccacab34ddd2c9b76/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml#L71
https://github.com/wazuh/wazuh-ansible/blob/52a81af988a00abd60483f1ccacab34ddd2c9b76/roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml#L62

- The loadbalancer will redirect the registration queries as stated in [wazuh-master-svc.yaml](https://github.com/wazuh/wazuh-kubernetes/blob/4f9f79fdb5a39ae86c96995a52bd79472517ecc3/wazuh_managers/wazuh-master-svc.yaml#L21-L32)

### Wazuh on kubernetes/architecture without loadbalancer 

- In this case you could declare several `wazuh_manager` instances, taking into account that the first one manager IP address will be considered as the one in charge of agents registration:

```YAML
       vars:
         wazuh_managers:
           - address: master-ip
             port: 1514
             protocol: tcp
             api_port: 55000
             api_proto: 'http'
             api_user: 'ansible'
           - address: worker-ip
             port: 1514
             protocol: tcp
             api_port: 55000
             api_proto: 'http'
             api_user: 'ansible'
.
.
.
.
```

As a bonus you could create a new variable, replace the one on windows/linux agents registration tasks `-m {{ wazuh_managers.0.address }} ` so you can specify it explicitly.

Greetings, 
JP Sáez
