### ISSUE TITLE
Improve handling of run_once at opendistro-elasticsearch role

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh-ansible#476]
Hello everyone!

### Purpose

The proposal is to switch from importing to including tasks for `security_action.yml` at `roles/opendistro/opendistro-elasticsearch/tasks/main.yml` and also, to extract the `when` and `tag` clause to the including task, like so:

```yaml
  - include_tasks: security_actions.yml
    tags:
      - security
    when: install.changed
```

This allows for better evaluation of `run_once` clause for scenarios where a playbook including the role runs multiple times and the tasks are mistakenly evaluated as already run and thus, no internal_user  related tasks are run and deployment stops at task ` Wait for Elasticsearch API`. This fixes ODFE scenario for issue  #463

I'll include a branch with these changes.

Regards
