### ISSUE TITLE
"include_vars" statement overrides variable set elsewhere (e.g., in inventory)

### ISSUE THREAD

**Issue by dragospe** [wazuh/wazuh-ansible#488]
Hello, 

I'm not certain this is a proper "issue" or just a matter of taste, but the way that "include_vars"  is used in some playbooks leads to unexpected results.

In particular, I've noticed that the file `roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml` has a handful of tasks such as 

```
- name: Retrieving authd Credentials
  include_vars: authd_pass.yml
  tags:
    - config
```

that obliterate the variable if it is declared elsewhere; for instance, as a group variable, within inventory, or as a task variable.

My proposal would be to move the contents of `authd_pass.yml` to a `vars/main.yml` within the role, and letting standard variable precedence do the work; this proposal would hold for other vars files that are intended to be user-configurable.
