### ISSUE TITLE
Confusion surrounding how to register agents

### ISSUE THREAD

**Issue by dragospe** [wazuh/wazuh-ansible#502]
I am having some difficulty understanding how to register agents using the `ansible-wazuh-agent` role. I managed to work around the problem (and subsequently forgot what I did to do so), but I'd like to understand what the original intention was, and hopefully add these to the documentation.

There's a good chance I'm just misunderstanding something fundamental, but I would appreciate it if someone could help troubleshoot and subsequently review my edits to the docs. 

-------------

I modified the example playbook to my environment:

```
- hosts: agents
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 192.168.122.6
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
    wazuh_agent_authd:
      registration_address: 192.168.122.6
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
```

but running this gives me

```
TASK [../roles/wazuh/ansible-wazuh-agent : Linux | Register agent (via authd)] ***
fatal: [gitea.test]: FAILED! => {"msg": "The conditional check 'not check_keys.stat.exists or check_keys.stat.size == 0' failed. The error was: error while evaluating conditional (not check_keys.stat.exists or check_keys.stat.size == 0): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/pdragos/ansible/arctan_ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml': line 83, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Linux | Register agent (via authd)\n      ^ here\n"}
```

Putting in a debug statement before that task shows:

```
TASK [../roles/wazuh/ansible-wazuh-agent : debug] ******************************
ok: [gitea.test] => {
    "check_keys": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
ok: [nc.test] => {
    "check_keys": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

Which makes sense, because the following task only checks when `wazuh_agent_config.enrollment.enabled == 'yes'`:

```
- name: Linux | Check if client.keys exists
  stat: path=/var/ossec/etc/client.keys
  register: check_keys
  when: wazuh_agent_config.enrollment.enabled == 'yes'
  tags:
    - config
```
This variable doesn't seem to be listed in the [variables reference](https://documentation.wazuh.com/4.0/deploying-with-ansible/reference.html), but I tried setting it to yes in the playbook anyways.  The playbook runs through without error, but no agents are registered.

Taking a look at `roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml`, we see that the block "Linux | Agent registration via authd" only runs when:

```
when:
    - wazuh_agent_authd.enable
    - not wazuh_agent_config.enrollment.enabled | length > 0 or wazuh_agent_config.enrollment.enabled == 'no'
```
and the block "Linux | Agent registration via rest-API" only runs when

```
  when:
    - not wazuh_agent_authd.enable
    - not wazuh_agent_config.enrollment.enabled | length > 0 or wazuh_agent_config.enrollment.enabled == 'no'
```

Which leads me to wonder what the variable  `wazuh_agent_config.enrollment.enabled` actually means. Is it:

1.) A variable indicating that the agent is already enabled, which is why it skips registration?
2.) A variable indicating that the agents *should* be enabled?

Either way, I'm confused about what set of options was intended by the developer.

**Comment by Zenidd** [comment]
Hi @dragospe,

first of all, thank you for taking the time to write such a nice described issue. 

>  but I'd like to understand what the original intention was, and hopefully add these to the documentation.

Sure, let me explain the differences between the current and the previous playbook structure and variables:

## wazuh-agent role and agents registration in Wazuh 3.x

- In Wazuh 3.x, agents should be manually registered after install (they didn't have any auto-register feature). It was done through the `agent-auth` binary or the API method. 
- `wazuh-agent` role used the `agent-auth` option by default. The hereunder v3.13.2 wazuh-agent example playbook contains the authd section:

```yaml
 vars: 
   wazuh_managers: 
     - address: <your manager IP> 
       port: 1514 
       protocol: udp 
       api_port: 55000 
       api_proto: 'http' 
       api_user: ansible 
       max_retries: 5 
       retry_interval: 5 
   wazuh_agent_authd: 
     registration_address: <registration IP> 
     enable: true 
     port: 1515 
     ssl_agent_ca: null 
     ssl_auto_negotiate: 'no' 
```
`wazuh_managers.address`: the IP here will be the one the agent `ossec.conf`, and the one the agent will report to.
`wazuh_agent_authd.registration_address` the agent will try to register against this address.


## wazuh-agent role and agents registration in Wazuh 4.x

- Since Wazuh 4.0, by default, the agent registers automatically with the manager through enrollment.
- `wazuh-agent` role now uses enrollment by default.
- The current `wazuh-agent` v4.0.1 example playbook has no authd related section

```yaml
- hosts: <your wazuh agents hosts>
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: <your manager IP>
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
```


## OK, but the current wazuh-agent playbook is not working

- Apart from all this, using the default playbook causes a registration error. This is due to the enrollment `enable` variable having an empty string value:
https://github.com/wazuh/wazuh-ansible/blob/6e72daa737965307f50e50ab6ad042bb8f250a0f/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L91-L92

Setting enrollment to `yes` in the default values or in the `wazuh-agent` playbook leads to a smooth deployment with no errors. We are opening a PR setting the default to this proper value.


### another issue on agents registrations

After checking that enrollment works I disabled it and tried the agent-auth method. It threw an error related to the registration verification. After some tests, I realized that the output for `agent-auth` has changed and the string we checked for `Valid key created` has turned into `Valid key received`. The PR related to this issue will also include that fix.

OLD agent-auth logs:
```
[root@agent-client-1 vagrant]# /var/ossec/bin/agent-auth  -m 172.16.0.101 -p 1515       
2020/11/20 12:12:22 agent-auth: INFO: Started (pid: 15513).
2020/11/20 12:12:22 agent-auth: INFO: Starting enrollment process to server: 172.16.0.101
2020/11/20 12:12:22 agent-auth: INFO: Connected to 172.16.0.101:1515
2020/11/20 12:12:22 agent-auth: INFO: Registering agent to unverified manager.
2020/11/20 12:12:22 agent-auth: INFO: No authentication password provided.
2020/11/20 12:12:22 agent-auth: INFO: Using agent name as: agent-client-1
2020/11/20 12:12:22 agent-auth: INFO: Request sent to manager
2020/11/20 12:12:22 agent-auth: INFO: Waiting for manager reply
2020/11/20 12:12:22 agent-auth: INFO: Received response with agent key
2020/11/20 12:12:22 agent-auth: INFO: Valid key created. Finished.
2020/11/20 12:12:22 agent-auth: INFO: Connection closed.
```

Current agent-auth logs:
```
[root@agent-client-1 vagrant]# /var/ossec/bin/agent-auth  -m 172.16.0.101 -p 1515       
2020/11/20 12:12:55 agent-auth: INFO: Started (pid: 16407).
2020/11/20 12:12:55 agent-auth: INFO: Requesting a key from server: 172.16.0.101
2020/11/20 12:12:55 agent-auth: INFO: No authentication password provided
2020/11/20 12:12:55 agent-auth: INFO: Using agent name as: agent-client-1
2020/11/20 12:12:55 agent-auth: INFO: Waiting for server reply
2020/11/20 12:12:55 agent-auth: INFO: Valid key received
```

Seems like we should review the examples on https://documentation.wazuh.com/4.0/deploying-with-ansible/roles/wazuh-agent.html. 

I hope it helps. Greetings,

JP
