### ISSUE TITLE
wazuh-agent role install task timeouts on slow CentOS machines

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh-ansible#506]
Hi team,

From time to time we've been observing this behaviour in molecule tests on slow machines:

```yaml
 TASK [../../roles/wazuh/ansible-wazuh-agent : Linux CentOS/RedHat | Install wazuh-agent] ***
    task path: /home/runner/work/wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml:21
    META: noop
    META: noop
    META: noop
    META: noop
    META: noop
    skipping: [wazuh_agent_debian9] => {"changed": false, "skip_reason": "Conditional result was False"}
fatal: [wazuh_agent_centos7]: FAILED! => {"changed": false, "msg": "async task did not complete within the requested time - 90s"}
```

This bug was inadvertently introduced by the commit trying to address issue #29 and pops from time to time, according to machine stress. The refreshed solution to the lock file issue would be removing async and adding the option `lock_timeout` to `yum` module.
