### ISSUE TITLE
Ansible Collection

### ISSUE THREAD

**Issue by keilr** [wazuh/wazuh-ansible#545]
I'm new to Wazuh and I was very happy to find this official Wazuh Ansible repository! Great work!

It would be nice to enhance this project by aligning it to the [Ansible collection](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html) format so one can easily install the playbooks and roles by using the Ansible Galaxy cli-tool. Roles could be accessed by name instead of paths. Adding it to the Ansible Galaxy repository should be considered.

## Installation

From galaxy ...

    ansible-galaxy collection install wazuh.wazuh

... or from github repo and stable branch

    ansible-galaxy collection install git+https://github.com/wazuh/wazuh-ansible.git,stable   

(requires `ansible>=2.10`)

## Using Roles

```
---
- hosts: host001
  roles:
    - wazuh.wazuh.agent
  vars:
    wazuh_managers:
      - address: ...
      ...
```
