### ISSUE TITLE
Provide a means to select the installed version number

### ISSUE THREAD

**Issue by memelet** [wazuh/wazuh-ansible#59]
There should be a means to select the installed version. For example in ansible-wazuh-manager/agent"latest" is always used.
```
- name: Install wazuh-manager, wazuh-api and expect
  package: pkg={{ item }} state=latest
  with_items:
    - wazuh-manager
    - wazuh-api
    - expect
```

**Comment by memelet** [comment]
Seems that an agent version is supported for windows
```
wazuh_winagent_config:
  version: '3.3.1'
  ...
```

**Comment by memelet** [comment]
Hmm, ok. Then I guess we would just maintain a fork or lock into a git revision. So I'll withdraw the issue.

**Comment by memelet** [comment]
Back to versions... When installing say the agent, the playbook does

```
- name: Linux | Install wazuh-agent
  package: name=wazuh-agent state=present
  async: 90
  poll: 15
  tags:
    - init
```
Which installs the "latest". If the playbooks are updated to reflect the current version, what happens for those running a version behind? Could it be the case that the 3.6 playbooks will break with the version of the agent (or other "latest" bits) that the 3.6 playbooks have been updated for?

Even if the version's are not configurable, it seems they should still be explicit.
