### ISSUE TITLE
How to provide local_rules.xml?

### ISSUE THREAD

**Issue by memelet** [wazuh/wazuh-ansible#60]
The changelog indicates "allow providing own local_rules.xml template with var ossec_server_… #5 (By pull request: recunius (Thanks!))". But this does not seem to be implemented anywhere. Is this changelog left over from the dj-wasabi version?

```
- name: Installing the local_rules.xml (default local_rules.xml)
  template: src=var-ossec-rules-local_rules.xml.j2
            dest=/var/ossec/etc/rules/local_rules.xml
            owner=root
            group=ossec
            mode=0640
  notify: restart wazuh-manager
  tags:
    - init
    - config
    - rules
```

**Comment by memelet** [comment]
Yes, it looks like this feature got dropped. From the dj-wasabi repo
```
- name: "Installing custom local_rules.xml"
  template:
    src: "{{ playbook_dir }}/{{ ossec_server_config.local_rules_template }}"
    dest: /var/ossec/rules/local_rules.xml
    owner: root
    group: root
    mode: 0644
  when:
    - ossec_server_config.local_rules_template is defined
  notify:
    - restart ossec-server
  tags:
    - init
    - config
    - rules

- name: "Installing the local_rules.xml (default local_rules.xml)"
  template:
    src: var-ossec-rules-local_rules.xml.j2
    dest: /var/ossec/rules/local_rules.xml
    owner: root
    group: root
    mode: 0644
  when:
    - ossec_server_config.local_rules_template is not defined
  notify:
    - restart ossec-server
  tags:
    - init
    - config
    - rules
```
