### ISSUE TITLE
Debian: Remove repository tasks do not work due to wrong hardcoded repository string

### ISSUE THREAD

**Issue by fraform-tnz** [wazuh/wazuh-ansible#603]
Hi all. I noticed that the tasks used to remove APT repo from Debian systems, use wrong hardcoded APT repo string which is different from current (and correct) one. For example for the agent role we have:

**defaults/main.yml**
```
wazuh_agent_repo:
    apt: 'deb https://packages.wazuh.com/4.x/apt/ stable main'
```

**tasks/Debian.yml**
```
- name: Debian/Ubuntu | Add Wazuh repositories
  apt_repository:
    filename: wazuh_repo
    repo: "{{ wazuh_agent_config.repo.apt }}"
    state: present
    update_cache: true
```
    
**tasks/RMDebian.yml**
```
- name: Remove Wazuh repository (and clean up left-over metadata)
  apt_repository:
    repo: deb https://packages.wazuh.com/apt {{ ansible_distribution_release }} main
    state: absent
  changed_when: false
```

As you can see in last snippet the repo string is different from the content of "wazuh_agent_repo.apt" var, and so the tasks simply don't remove the repo.

This happens also for unistall.yml task executed in manager role. As suggestion it could be used the `wazuh_agent_repo.apt` var also in these tasks.

Thanks.
