### ISSUE TITLE
Issue when using AnsibleVault for authd_pass on agents deployment

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh-ansible#628]
Hello team,

When using an `AnsibleVault` secret for the Wazuh Agent deployment, we find the following error:

```
fatal: [192.168.1.41]: FAILED! => {"msg": "The conditional check 'authd_pass | length > 0' failed. The error was: Unexpected templating type error occurred on ({% if authd_pass | length > 0 %} True {% else %} False {% endif %}): object of type 'AnsibleVaultEncryptedUnicode' has no len()\n\nThe error appears to be in '/etc/ansible/roles/wazuh-ansible/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml': line 245, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create auto-enrollment password file\n  ^ here\n"}
```

## Steps to reproduce:

1. Create the AnsibleVault secret:

```
ansible-vault encrypt_string "P@SSW0RD"
```

2. Configure the `authd_pass` variable on `roles/wazuh/ansible-wazuh-agent/defaults/main.yml` :

```yaml
 # We recommend the use of ansible-vault to protect Wazuh, api, agentless and authd credentials.
api_pass: wazuh
authd_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61366566623337313632383939383164346661326562643635333632353635636565313436613931
          3831333234323133306534383934323937316166626137370a366161613139623261313066333134
          65653133326134613037373237633030613536646430303636656566643139386538633663663232
          3662656536653864300a646265666634356330376461613664376432363362383162366565376230
          3632
```

3. Configure the `wazuh-agent` Playbook as follows:

```yaml
---
- hosts: agents
  become: yes
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 192.168.1.30
        port: 1514
        protocol: tcp
        max_retries: 5
        retry_interval: 5
    wazuh_agent_authd:
      registration_address: 192.168.1.30
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
```

4. Execute the Playbook:

```
ansible-playbook playbooks/wazuh-agent.yml -b -K --ask-vault-pass
```

Let me know if you need any further information.

Regards,
Franco Hielpos
