### ISSUE TITLE
Stretch Backports Debian repository key missing

### ISSUE THREAD

**Issue by colans** [wazuh/wazuh-ansible#647]
*I created a new issue because #605 was closed and I couldn't figure out how to reopen it.*

```
TASK [opendistro-elasticsearch : Add openjdk repository] ***********************
task path: /path/to/repo/roles/opendistro/opendistro-elasticsearch/tasks/Debian.yml:12
[...]
fatal: [AAA.BBB.CCC.DDD]: FAILED! => {
    "changed": false
}
```

> Failed to update apt cache: W:GPG error: http://deb.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9, E:The repository 'http://deb.debian.org/debian stretch-backports InRelease' is not signed.

The task is:

```yml
- name: Add openjdk repository
  apt_repository:
    repo: "{{ package_repos.apt.openjdk.baseurl }}"
    state: present
    update_cache: yes
```

...and from the defaults file:

```yml
      baseurl: 'deb http://deb.debian.org/debian stretch-backports main'
```

We should be able to simply import the key in a task before adding repo.  I'll try that and report back.

**Comment by colans** [comment]
### Proposal

Adding this task before the one above seems to work:

```yml
    - name: Add the repository key for Debian's Stretch Backports repository
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 648ACFD622F3D138
```

Please include this or something comparable.

### Workaround

Add the above task to your `pre_tasks` in your playbook.

```yml
  pre_tasks:
    # TODO: Remove this when https://github.com/wazuh/wazuh-ansible/issues/647 is resolved.
    - name: Add the repository key for Debian's Stretch Backports repository
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 648ACFD622F3D138
```
