### ISSUE TITLE
Fix wazuh_api_credentials and wazuh_api_users

### ISSUE THREAD

**Issue by itprogression** [wazuh/wazuh-ansible#677]
wazuh_api_credentials is used to parameterize:

```
      wazuh_api_credentials:
        - id: "default"
          url: "https://localhost"
          port: 55000
          username: "wazuh"
          password: "wazuh"
```

But when using: wazuh_api_users

```
      wazuh_api_users:
        - username: wazuh
          password: .S3cur3Pa55w0rd*
```

Elastic / Kibana loses connection to the Wazuh API. Since the config file does not update the credentials.
