### ISSUE TITLE
filebeat openedistro authentication failed

### ISSUE THREAD

**Issue by alyvusal** [wazuh/wazuh-ansible#687]
Hi
When I use different password than `changeme`, filebeat on wazuh cluster nodes can not authenticate to opendistro-elasticsearch.
Changing password on file /etc/filebeat/filebeat.yml resolves issue
Passwords and certificate path are hard coded which is better to use variable instead

Files uses this password
```
roles/wazuh/ansible-filebeat-oss/defaults/main.yml:15:elasticsearch_security_password: changeme
roles/opendistro/opendistro-kibana/defaults/main.yml:43:opendistro_admin_password: changeme
roles/opendistro/opendistro-kibana/defaults/main.yml:45:opendistro_kibana_password: changeme
roles/opendistro/opendistro-elasticsearch/defaults/main.yml:62:opendistro_admin_password: changeme
roles/opendistro/opendistro-elasticsearch/defaults/main.yml:63:opendistro_kibana_password: changeme
```

deployment was with production-ready playbook with custom variables

**Comment by teddytpc1** [comment]
Hi @alyvusal.
I will need your playbook with the custom variables you are using. Can you remove/replace sensitive information and share it?
I am working on a fix for the `filebeat.yml` but it will be better if I test your playbook in order to make sure it is working properly.
Also, I will need to know what `wazuh-ansible` `version/tag` are you using.
Thanks.

**Comment by alyvusal** [comment]
@teddytpc1 , Hi, related variables:

```yaml
wazuh_api_credentials:
  - id: master
    url: https://{{ hostvars.wazuhmaster01.private_ip }}
    port: 55000
    username: wazuhapiadmin
    password: MyPass123$test

wazuh_api_users:
  - username: wazuhapiadmin
    password: MyPass123$test

opendistro_admin_password: MyPass123$test
opendistro_kibana_password: MyPass123$test
```
added custom fix task after deployment
```yaml
    - name: Change user /etc/filebeat/filebeat.yml
      ansible.builtin.lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: 'password: changeme'
        line: "  password: {{ opendistro_kibana_password }}"
        backup: yes
      notify: restart filebeat
```
and this is main playbook

```yaml
---
# Certificates generation
- hosts: wazuhopendistro01
  roles:
    - role: wazuh-ansible/roles/opendistro/opendistro-elasticsearch
      elasticsearch_network_host: "{{ ansible_host }}"
      perform_installation: false

# ODFE Cluster
- hosts: opendistro
  strategy: free
  roles:
    - role: wazuh-ansible/roles/opendistro/opendistro-elasticsearch
      elasticsearch_network_host: "{{ ansible_host }}"

# Wazuh cluster
- hosts: master
  roles:
    - role: "wazuh-ansible/roles/wazuh/ansible-wazuh-manager"
    - role: "wazuh-ansible/roles/wazuh/ansible-filebeat-oss"

- hosts: worker
  roles:
    - role: "wazuh-ansible/roles/wazuh/ansible-wazuh-manager"
    - role: "wazuh-ansible/roles/wazuh/ansible-filebeat-oss"

# ODFE+Kibana node
- hosts: kibana
  roles:
    - role: "wazuh-ansible/roles/opendistro/opendistro-elasticsearch"
    - role: "wazuh-ansible/roles/opendistro/opendistro-kibana"
```

I think it will help to you
