### ISSUE TITLE
How to add a wazuh worker to an already deployed environnement with wazuh-odfe-production-ready playbook ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [wazuh/wazuh-ansible#759]
Hi, I didn't find any information to add an other worker in an already deployed environnement with the wazuh-odfe-production-ready playbook.
I would like to add two wazuh worker with the same certificates create in `wazuh-ansible-4.2.6/playbooks/opendistro/certificates/certs/` during the deployement with the wazuh-odfe-production-ready playbook.
Thanks for any advise on this.

**Comment by teddytpc1** [comment]
Hi @NRGLine4Sec.
You will have to perform the following actions:
1. Add the new worker node to the inventory file:
`worker02  ansible_host=<worker02_node_public_ip> private_ip=<worker02_private_ip>`
2. Modify the wazuh-odfe-production-ready.yml to add the new `worker`:
```
    - hosts: worker02
      roles:
        - role: "../roles/wazuh/ansible-wazuh-manager"
        - role: "../roles/wazuh/ansible-filebeat-oss"
          filebeat_node_name: node-7
      become: yes
      become_user: root
      vars:
        wazuh_manager_config:
          connection:
              - type: 'secure'
                port: '1514'
                protocol: 'tcp'
                queue_size: 131072
          api:
              https: 'yes'
          cluster:
              disable: 'no'
              node_name: 'worker_02'
              node_type: 'worker'
              key: 'c98b62a9b6169ac5f67dae55ae4a9088'
              nodes:
                  - "{{ hostvars.manager.private_ip }}"
              hidden: 'no'
        filebeat_output_elasticsearch_hosts:
                - "{{ hostvars.es1.private_ip }}"
                - "{{ hostvars.es2.private_ip }}"
                - "{{ hostvars.es3.private_ip }}"
```
3. Modify the wazuh-odfe-production-ready.yml to add the new `worker` to the instances list. For every instance list you will have to add the `node7`. e.g.:
```
          node7:
            name: node-7
            ip: "{{ hostvars.worker02.private_ip }}"
```
4. Move the `opendistro/certificates` directory. In order to recreate a new set of certificates (including the new Worker node) you will have to move the directory.
5. Execute the playbook again using the modified playbook and inventory.
