### ISSUE TITLE
New templates for agents. 

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-ansible#78]
Hello team, 

Referring to the issue #77, 

To complement the quick response solution, but doing a more detailed work, we will proceed to create different configuration templates of the agent depending on the operating system in which it is installed to avoid errors monitoring non-existent directories and to avoid losing events by not monitoring files as for example was the case of /var/logs/auth.log.

Therefore, we should identify the main cases like RPM, DEBIAN and WINDOWS (where we install agents via ansible) and create a specific configuration, adapting it if necessary to specific versions. This work will be useful in the future when we share the configurations from the manager using the groups. 

Additionally, we should replicate what we do in a simple installation and keep the configuration shared from the empty manager. 

Regards,

Alfonso

**Comment by manuasir** [comment]
Hi team,

Regarding this issue, I just realized that the Windows `ossec.conf` file is not being generated completely. For example, the default directories to be ignored by syscheck according to the documentation are not being included on it.

Thanks

**Comment by paulcalabro** [comment]
Nice that you guys are considering restructuring this! I was actually thinking of making a PR for this. What I'd recommend is something like this:

```
- name: Include variables based on distribution and operating system family
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - default.yaml
```

...and then create the **same** variable in each YAML file with the appropriate values based on the distribution and operating system family.
