### ISSUE TITLE
`wazuh-indexer` role cannot be installed in ALAS when running on ECS

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-ansible#825]
# Description

After trying to install the indexer in a ECS instance, the following error was raised:

```bash
bash: sysctl: command not found
```

This occurs when running this [task](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/wazuh-indexer/tasks/RedHat.yml#L31-L33):
```yaml
- name: Update vm.max_map_count
    shell: sysctl -p
    become: yes
```
We can't use `sysctl` within a Container instance.
