### ISSUE TITLE
indexer_version issue

### ISSUE THREAD

**Issue by atcommander** [wazuh/wazuh-ansible#842]
When I use the 4.3 branch of this repo, the indexer_version is set to the default value 4.3.8

When the following check happens in the wazuh-indexer role in the tasks file main.yml, it registers the variable as wazuh_latest_release as 4.3.7 which causes the unstable repos to be setup rather than the stable ones.  Also I noticed that if I use the stable branch then it defaults to setting up 4.3.6.

```yaml
- name: Get latest wazuh release
  shell: "curl --silent https://api.github.com/repos/wazuh/wazuh/releases/latest | grep '\"tag_name\":' | sed -E 's/.*\"([^\"]+)\".*/\\1/'| cut -c 2-"
  register: wazuh_latest_release
```

I was following the documentation at https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html which instructs you to use branch 4.3 so I think the default value for indexer_version needs to be changed.
