### ISSUE TITLE
Update the vulnerability detector default configuration block with missing providers

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-ansible#975]
### Description

The vulnerability detector compatibility matrix shows that some providers are missing in the default configuration of this repository

https://documentation.wazuh.com/4.4/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix

The corresponding block should be updated with the missing entries.

### DoD

- [ ] Add SUSE to the vulnerability detector configuration
- [ ] Add ALAS to the vulnerability detector configuration
- [ ] Add Arch to the vulnerability detector configuration
- [ ] Add MSU to the vulnerability detector configuration

**Comment by davidcr01** [comment]
# Update Report

The missing providers have been added to the `roles/wazuh/ansible-wazuh-manager/defaults/main.yml` file with the following content, related to https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/vuln-detector.html#example-of-configuration

```yml
- enabled: 'no'
  os:
    - 'amazon-linux'
    - 'amazon-linux-2'
  update_interval: '1h'
  name: '"alas"'
- enabled: 'no'
  update_from_year: '2010'
  update_interval: '1h'
  name: '"arch"'
- enabled: 'no'
  os:
    - '11-server'
    - '11-desktop'
    - '12-server'
    - '12-desktop'
    - '15-server'
    - '15-desktop'
  update_interval: '1h'
  name: '"suse"'
- enabled: 'no'
  update_from_year: '2010'
  update_interval: '1h'
  name: '"msu"'
```
